from setuptools import find_packages, setup

setup(
    name='predicting-solid-state-materials-for-quantum-technology',
    version='1.0.0',
    packages=find_packages(),
    install_requires=['typing',
        'pandas',
        'python-dotenv',
        'click',
        'pymatgen<=2021.3.3',
        'matminer<0.7',
        'pathlib',
        'tqdm',
        'numpy',
        'jarvis',
        'aflow',
        'matplotlib',
        'plotly',
        'sklearn',
        'seaborn',
        'datetime',
        'imblearn',
        'setuptools',
        'virtualenvwrapper',
        'virtualenv',
        'wget',
        'python-dotenv',
        'kaleido',
        'citrination-client',
        'shap',
        'tikzplotlib',
        'mdf_forge',
        'jupyter==1.0.0'],
    classifiers=[
        'Programming Language :: Python :: 3.8',
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
    description='This is the main repository behind predicting solid state qubit candidates',
    author='Oliver Lerstøl Hebnes',
    license='MIT',
)
